# -*- coding: utf-8 -*-
"""Evaluating the Impact of Spread Density Standards on Shrimp Farmers’ Productivity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JwScSc1Bj8eaBNaLnOkP7OTQhp3LcYK

**<h1>🦐 Evaluating the Impact of Spread Density Standards on Shrimp Farmers Productivity</h1>**

*Analysis of the Relationship Between Spread Density Standards and Shrimp Farmers Productivity by Rizki Primadhany Syahputri & Ibra Aryani*

<hr>

#**INTRODUCTION**

Spread density is a key factor affecting cumulative harvest weight, productivity, survival rate (SR), and feed conversion ratio (FCR). Proper density selection, aligned with the cultivation method, optimizes growth efficiency and sustainability.

##**Spread Density Standards by Cultivation Type**

| Cultivation Type | Spread Density ((shrimp/m²) | Characteristics |
|---|---|---|
| Tradisional | 2 - 25 | Low-tech, minimal aeration, slow growth, lower risks |
| Semi-Intensive | 26 - 80 | Moderate aeration, better control over feed and water quality |
| Intensive | 75 - 600 | High-tech, strong aeration, high yield potential, requires strict management |

##**Impact of Spread Density on Productivity Metrics:**

*   **Cumulative Harvest Weight**: Increases with density up to an optimal point but declines with overcrowding.
*   **Productivity**: Higher in intensive systems but depends on proper water and feed management.
*   **Survival Rate (SR)**: Higher in lower densities; decreases in intensive systems if conditions are not well controlled.
*   **Feed Conversion Ratio (FCR)**: Most efficient in semi-intensive systems, worsens at very high densities due to feed competition and water quality issues.

Optimizing spread density according to cultivation type is essential for maximizing shrimp farm productivity. While higher densities can improve yield, exceeding optimal levels leads to stress, disease, and reduced efficiency. Proper management is key to sustainable success.

#**OBJECTIVE:**

This analysis aims to evaluate the relationship between standard spread densities and the productivity of shrimp farmers across three types of cultivation: traditional, semi-intensive, and intensive.

#**HYPOTHESIS:**

The hypothesis to be tested is that **compliance with the spread density standard will increase shrimp farmers' productivity**.

# **Data Preparation**

The data to be used is aquaculture data with the smallest granularity being the cycle (cycle_uuid) of 2024.

[Data Set Productivity Analysis](https://docs.google.com/spreadsheets/d/1bMrs4ddJm_f1CpxFAKvvwLOSAiAmHzZx1gga-WDKUug/edit?usp=sharing)
"""

# Import the required libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu

# Reading data from Google Spreadsheet
raw = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTMw_gtf95BWaIgAsFdVEDpcm_7VuJIs7gtV-jHeq986qPJmN3aUf7eApALaex24g98HJ-1hGhgluzE/pub?gid=0&single=true&output=csv'

df = pd.read_csv(raw)

# Displaying the first 5 rows of the data
df.head()

"""##**DESKRIPSI VARIABLE:**

Berikut adalah deskripsi variabel-variabel yang ada dalam dataset:

* **cycle_uuid:** Shrimp Cycle ID.
* **cultivation_type:** Cultivation Type (TRADITIONAL, SEMI-INTENSIVE, INTENSIVE).
* **spread_density:** Spread Density (shrimp/m²).
* **is_met_standard_spread_densities:** Whether the spread density meets the standard (0 = No, 1 = Yes).
* **cumulative_harvest_weight:** Cumulative harvest weight (kg).
* **productivity:** Productivity (kg/m²).
* **sr_harvest:** Harvest survival rate (%).
* **fcr_harvest:** Harvest feed conversion ratio.

# **Data Exploration**
"""

#Descriptive Statistic
df.describe()

"""From the descriptive statistics table, we can see an overall summary of the data.

- The **average cumulative harvest weight** (cumulative_harvest_weight) is approximately 1,025 kg, with a minimum value of 18 kg and a maximum of 2,567 kg.
- The **average productivity** (productivity) is around 3.4 kg/m², with a minimum value of 0.06 kg/m² and a maximum of 8.56 kg/m².
- The **average survival rate** at harvest (sr_harvest) is about 78%, with a minimum of 30% and a maximum of 98%.
- The **average feed conversion ratio** (fcr_harvest) is approximately 1.4, with a minimum value of 1.02 and a maximum of 2.17.
"""

#Descriptive Statistic for Productivity Parameters
df[['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']].describe()

# is_met_standard_spread_densities = 0
df[df['is_met_standard_spread_densities'] == 0][['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']].describe()

# is_met_standard_spread_densities = 1
df[df['is_met_standard_spread_densities'] == 1][['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']].describe()

"""#**Visualisasi Data**

##**Box Plot dan Violin Plot**

Here is the data visualization using **box plot** and **violin plot** to compare the distribution of **productivity** parameters between groups that meet and do not meet the **spread density** standard, based on the type of cultivation.
"""

# Definisikan parameters
parameters = ['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']

# Box Plot dengan hue
for param in parameters:
    plt.figure(figsize=(8, 6))
    sns.boxplot(x='is_met_standard_spread_densities', y=param, hue='cultivation_type', data=df)
    plt.title(f'Box Plot of {param} by Standard Spread Densities')
    plt.xlabel('Met Standard Spread Densities (0=No, 1=Yes)')
    plt.ylabel(param)
    plt.show()

# Violin Plot dengan hue
for param in parameters:
    plt.figure(figsize=(8, 6))
    sns.violinplot(x='is_met_standard_spread_densities', y=param, hue='cultivation_type', data=df)
    plt.title(f'Violin Plot of {param} by Standard Spread Densities')
    plt.xlabel('Met Standard Spread Densities (0=No, 1=Yes)')
    plt.ylabel(param)
    plt.show()

"""## **Interpretasi Box Plot {param}:**

**cumulative_harvest_weight**:

From the box plot, it can be seen that the **median cumulative harvest weight** tends to be higher in the group that meets the **spread density standard**, especially in **intensive farming**. This indicates that **meeting the spread density standard has the potential to increase harvest weight**.

**productivity**:

The box plot shows that the **median productivity** tends to be higher in the group that meets the **spread density standard** across all types of cultivation, especially in **intensive farming**. This indicates that **meeting the spread density standard can increase productivity**.

**sr_harvest**:

The box plot for **survival rate** at harvest does not show a significant difference between the groups that **meet** and **do not meet** the **spread density standard**. This indicates that the **spread density standard may not have a major impact on the survival rate**.

**fcr_harvest**:

The box plot shows that the **median FCR** tends to be **lower (better)** in the group that meets the **spread density standard**, especially in **intensive** and **semi-intensive farming**. A **lower FCR** indicates **better feed efficiency**, suggesting that **meeting the spread density standard can improve feed utilization efficiency**.

## **Interpretasi Violin Plot {param}:**

**cumulative_harvest_weight**:

The violin plot shows a **wider data distribution** in the group that meets the **spread density standard**, especially in **intensive farming**. This indicates a **greater variation in harvest weight** within that group.

**productivity**:

The violin plot shows a **more concentrated and higher data distribution** in the group that meets the **spread density standard**, especially in **intensive farming**. This indicates that **meeting the spread density standard can result in more consistent and higher productivity**.

**sr_harvest**:

The violin plot for **survival rate** at harvest shows a **relatively similar data distribution** between the groups that **meet** and **do not meet** the **spread density standard**. This supports the box plot conclusion that the **spread density standard may not have a significant impact on the survival rate**.

**fcr_harvest**:

The violin plot shows that the **FCR data distribution** tends to be **more concentrated at lower (better) values** in the group that meets the **spread density standard**, especially in **intensive** and **semi-intensive** farming. This indicates that **meeting the spread density standard can result in better and more consistent feed efficiency**.

#**Statistical Analysis**

##**Mann-Whitney U Test**

To **statistically test the hypothesis**, we will use the **Mann-Whitney U test**. This test is used to compare two independent data groups.
"""

parameters = ['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']

for param in parameters:
    group1 = df[df['is_met_standard_spread_densities'] == 0][param].dropna()
    group2 = df[df['is_met_standard_spread_densities'] == 1][param].dropna()
    statistic, p_value = mannwhitneyu(group1, group2)

    print(f"Mann-Whitney U test for {param}:")
    print(f"Statistic: {statistic}")
    print(f"P-value: {p_value}")

    # Interpretation of the p-value
    alpha = 0.05  # Significance level
    if p_value < alpha:
        print(f"The difference in {param} between the two groups is statistically significant (p < {alpha}).")
    else:
        print(f"There is no statistically significant difference in {param} between the two groups (p >= {alpha}).")
    print("-" * 20)

"""##**Interpretation:**

* **`cumulative_harvest_weight`:**

  The Mann-Whitney U test result for cumulative harvest weight shows a **p-value < 0.05**, indicating a **statistically significant difference** between the group that meets the **spread density standard** and the group that does not. This supports the hypothesis that **meeting the spread density standard increases harvest weight**.
* **`productivity`:**

  The Mann-Whitney U test result for productivity also shows a **p-value < 0.05**, indicating a **statistically significant difference** between the two groups. This supports the hypothesis that **meeting the spread density standard increases productivity**.
* **`sr_harvest`:**

  The Mann-Whitney U test result for survival rate shows a **p-value > 0.05**, meaning there is **no statistically significant difference** between the two groups. This suggests that **spread density standards do not have a significant impact on survival rate**.
* **`fcr_harvest`:**

  The Mann-Whitney U test result for FCR shows a **p-value < 0.05**, indicating a **statistically significant difference** between the two groups. This supports the hypothesis that **meeting the spread density standard improves feed efficiency (lowers FCR)**.

# **Conclusion dan Recommendation**

##**Conclusion:**

Based on the analysis conducted, it can be concluded that **meeting the spread density standard** is generally **associated with increased productivity and efficiency** in **shrimp farming**, especially in **intensive** and **semi-intensive** farming. The spread density standard does not have a significant impact on survival rate, but it can **increase cumulative harvest weight, productivity, and feed efficiency**.

##**Recommendation:**

Shrimp farmers are **advised to implement the appropriate spread density standard** based on the type of farming they practice. The government and relevant institutions can provide education and training to farmers on the importance of stocking density standards and the proper methods for their implementation.

##**Disclaimer:**

This analysis has several limitations, such as a limited sample size and data sourced from only one source. Further research with a larger sample size and more diverse data is needed to strengthen these conclusions.

#Others
Cultivation type : Intensive
"""

df_intensive = df[df['cultivation_type'] == 'INTENSIVE']

df_intensive[['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']].describe()

parameters = ['cumulative_harvest_weight', 'productivity', 'sr_harvest', 'fcr_harvest']

for param in parameters:
    group1 = df_intensive[df_intensive['is_met_standard_spread_densities'] == 0][param].dropna()
    group2 = df_intensive[df_intensive['is_met_standard_spread_densities'] == 1][param].dropna()
    statistic, p_value = mannwhitneyu(group1, group2)

    print(f"Mann-Whitney U test for {param}:")
    print(f"Statistic: {statistic}")
    print(f"P-value: {p_value}")

    # Interpretation of the p-value
    alpha = 0.05  # Significance level
    if p_value < alpha:
        print(f"The difference in {param} between the two groups is statistically significant (p < {alpha}).")
    else:
        print(f"There is no statistically significant difference in {param} between the two groups (p >= {alpha}).")
    print("-" * 20)